### ISSUE TITLE
LunCo - Lunar colony sim

### ISSUE THREAD

**Issue by 0xIonRod** [sarbian/MechJeb2#8]
Hi @sarbian .

I've seen you've being working on mods for KSP. 

I'm working on a similar but OPENSOURCE project: Lunar colony sim game

Is there any chance you'd like to collaborate?

[LunCo](https://github.com/lun-co/lunco-game)

**Comment by sarbian** [comment]
Hi

I am already not working enough on my own code. Taking another project, and even more so something as complex as a full game, is not something I am looking to do.
Best of luck for your project
